Implement MAC address generator with std::rand
B3n30/tunnler pull request #12
Opened 2017-03-23 08:51 UTC by B3n30

Implemented a mac address generator. The first 3 bytes are always 0x00 0x1F 0x32. This is a Nintendo OUI used with the 3ds. This ensures that none of the specials bits used with mac addresses isn't set. This isn't important for citra<->citra communication but gets important as soon as we send these data into real wifi. Also it ensures if any game would check for a nintendo vendor mac address. (I really doubt that, but just in case).

The last 3 bytes are generated randomly between 0x00 and 0xFF, each.

2017-03-23 12:49 UTC, Subv requested changes

2017-03-23 12:49 UTC, Subv commented on src/room.cpp
> +    stream.Write(member.mac_address.size());
Why?

2017-03-23 12:49 UTC, Subv commented on src/room.cpp
> +        for(int i = 3; i <= 5; ++i) {
Leave a space between the keyword and the (

2017-03-23 12:49 UTC, Subv commented on src/room.cpp
> +    MacAddress result_mac=NintendoOUI;
Space before and after the =

2017-03-23 12:49 UTC, Subv commented on src/room.cpp
> +        for(int i = 3; i <= 5; ++i) {
< address.size() instead of <=5

2017-03-23 12:49 UTC, Subv commented on src/room.cpp
> +    std::srand(std::time(0));
Use one of the C++11 random generators instead of the C random engine.

2017-03-25 13:10 UTC, Subv requested changes

2017-03-25 13:10 UTC, Subv commented on src/room.cpp
> +    for(auto it: member.mac_address) {
Why a loop instead of using the Write template directly?

2017-03-25 13:10 UTC, Subv commented on src/room_member.cpp
> +    stream.Read(reinterpret_cast<char*>(mac_address.data()), mac_address.size());
What use this? You can read the address directly with Read(mac_address)

2017-03-25 13:12 UTC, B3n30 commented on src/room.cpp
> +    for(auto it: member.mac_address) {
To ensure that RakNet handles the endianess in the right way

2017-03-25 13:20 UTC, Subv commented on src/room.cpp
> +    for(auto it: member.mac_address) {
That doesn't really tell me anything, why doesn't it handle endianness correctly if we use the array directly?

2017-03-25 13:43 UTC, B3n30 commented on src/room.cpp
> +    for(auto it: member.mac_address) {
Addressed

2017-03-25 13:43 UTC, B3n30 commented on src/room_member.cpp
> +    stream.Read(reinterpret_cast<char*>(mac_address.data()), mac_address.size());
Addressed

2017-03-25 21:14 UTC, Subv approved these changes
LGTM, squash and merge

2017-03-25 22:46 UTC, merged

2017-03-25 22:54 UTC, JayFoxRox commented
This made it uncompilable for me.

```
In file included from /usr/include/c++/6.3.1/random:49:0,
                 from /home/fox/Data/Projects/tunnler/include/tunnler/room.h:11,
                 from /home/fox/Data/Projects/tunnler/src/room.cpp:7:
/usr/include/c++/6.3.1/bits/random.h: In instantiation of ‘class std::uniform_real_distribution<unsigned char>’:
/home/fox/Data/Projects/tunnler/src/room.cpp:195:48:   required from here
/usr/include/c++/6.3.1/bits/random.h:1704:7: error: static assertion failed: template argument not a floating point type
       static_assert(std::is_floating_point<_RealType>::value,
       ^~~~~~~~~~~~~
/home/fox/Data/Projects/tunnler/src/room.cpp: In member function ‘MacAddress Room::GenerateMacAddress()’:
/home/fox/Data/Projects/tunnler/src/room.cpp:195:55: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     std::uniform_real_distribution<uint8_t> dis(0, 256); //Random byte between 0 and 0xFF
                                                       ^
In file included from /usr/include/c++/6.3.1/random:49:0,
                 from /home/fox/Data/Projects/tunnler/include/tunnler/room.h:11,
                 from /home/fox/Data/Projects/tunnler/src/room.cpp:7:
/usr/include/c++/6.3.1/bits/random.h: In instantiation of ‘struct std::__detail::_Adaptor<std::mersenne_twister_engine<long unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>, unsigned char>’:
/usr/include/c++/6.3.1/bits/random.h:1817:6:   required from ‘std::uniform_real_distribution<_RealType>::result_type std::uniform_real_distribution<_RealType>::operator()(_UniformRandomNumberGenerator&, const std::uniform_real_distribution<_RealType>::param_type&) [with _UniformRandomNumberGenerator = std::mersenne_twister_engine<long unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>; _RealType = unsigned char; std::uniform_real_distribution<_RealType>::result_type = unsigned char]’
/usr/include/c++/6.3.1/bits/random.h:1809:51:   required from ‘std::uniform_real_distribution<_RealType>::result_type std::uniform_real_distribution<_RealType>::operator()(_UniformRandomNumberGenerator&) [with _UniformRandomNumberGenerator = std::mersenne_twister_engine<long unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>; _RealType = unsigned char; std::uniform_real_distribution<_RealType>::result_type = unsigned char]’
/home/fox/Data/Projects/tunnler/src/room.cpp:198:43:   required from here
/usr/include/c++/6.3.1/bits/random.h:160:2: error: static assertion failed: template argument not a floating point type
  static_assert(std::is_floating_point<_DInputType>::value,
  ^~~~~~~~~~~~~
```

2017-03-25 22:55 UTC, JayFoxRox commented on src/room.cpp
> +    std::uniform_real_distribution<uint8_t> dis(0, 256); //Random byte between 0 and 0xFF
this should *probably* be an `int_distribution` :P

2017-03-25 22:56 UTC, B3n30 commented on src/room.cpp
> +    std::uniform_real_distribution<uint8_t> dis(0, 256); //Random byte between 0 and 0xFF
Do you want to create a fixup PR or should I?

2017-03-25 22:57 UTC, JayFoxRox commented on src/room.cpp
> +    std::uniform_real_distribution<uint8_t> dis(0, 256); //Random byte between 0 and 0xFF
wait.. it should also be 0, 255. You do it please - I've got other things to worry about currently.