added packet filter for beacon packets
B3n30/tunnler pull request #7
Opened 2017-03-22 13:28 UTC by B3n30

This is the filter algorithm for the beacon sender. Since sender mac will never be the broadcast mac setting filter to the broadcast mac, will give all the beacons stored in the deque

2017-03-22 13:32 UTC, JayFoxRox commented on src/room_member.cpp
> +        return result_queue;
I suggest moving this to a lambda or even a real function so we can re-use it for the data filter later (also you can give it a more descriptive name which makes the code more readable)

2017-03-22 13:41 UTC, B3n30 commented on src/room_member.cpp
> +        return result_queue;
I thought "PopWifiPackets" is exactly that function...

2017-03-22 14:22 UTC, B3n30 commented
Renamed the PR

2017-03-22 14:25 UTC, JayFoxRox commented on src/room_member.cpp
> +    auto FilterAndPopPackets = [=](std::deque<WifiPacket>* source_queue) {
Capture and pass by ref?

2017-03-22 14:25 UTC, JayFoxRox commented on src/room_member.cpp
>                  }else {
nit: missing a space (while you are at it anyway)

2017-03-22 14:26 UTC, JayFoxRox commented on src/room_member.cpp
> +        }
same thing: Probably want to use a lambda / function to avoid code duplication

2017-03-22 14:39 UTC, B3n30 commented on src/room_member.cpp
> +    auto FilterAndPopPackets = [=](std::deque<WifiPacket>* source_queue) {
Addressed

2017-03-22 14:39 UTC, B3n30 commented on src/room_member.cpp
>                  }else {
Addressed

2017-03-22 14:40 UTC, B3n30 commented on src/room_member.cpp
> +        }
Went for the lambda...

2017-03-25 13:18 UTC, Subv requested changes

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
> +    auto EmplaceBackAndCheckSize = [&](std::deque<WifiPacket>* queue, size_t maxSize) {
max_size.
Lower snake case for variables

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
> +    auto EmplaceBackAndCheckSize = [&](std::deque<WifiPacket>* queue, size_t maxSize) {
Why a pointer instead of a reference?

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
>          beacon_queue.emplace_back(std::move(wifi_packet));
You're calling emplace_back twice for beacons

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
>  std::deque<WifiPacket> RoomMember::PopWifiPackets(WifiPacket::PacketType type, const MacAddress& mac_address) {
Throughout all the files, leave a space after each flow control keyword.

If (mac_address == NoPreferredMac)

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
> +    auto FilterAndPopPackets = [&](std::deque<WifiPacket>* source_queue) {
Why a pointer instead of a reference?

2017-03-25 13:18 UTC, Subv commented on src/room_member.cpp
> +        return result_queue;
std::move(result_queue)

2017-03-25 13:51 UTC, B3n30 commented on src/room_member.cpp
> +        return result_queue;
"Moving a local object in a return statement prevents copy elision". Should i change it nevertheless

2017-03-25 13:53 UTC, B3n30 commented on src/room_member.cpp
> +    auto EmplaceBackAndCheckSize = [&](std::deque<WifiPacket>* queue, size_t maxSize) {
I'm somehow used to use pointers because of some stupid physics libraries...

2017-03-25 14:39 UTC, B3n30 commented
Addressed everything except return std::move(result_queue);

2017-03-25 20:05 UTC, Subv commented on src/room_member.cpp
> +        return result_queue;
Leave it, we want copy elision here, we can change it later if it produces sub-optimal code.

2017-03-25 20:06 UTC, Subv approved these changes
lgtm, squash and merge

2017-03-25 20:16 UTC, merged